# docker-compose.yml
version: "3.8"
services:
  web:
    hostname: wallet_web
    build: ./docker/nginx
    container_name: wallet_web
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www
    restart: always
    networks:
      - wallet-bridge
  php:
    hostname: wallet_php
    build: ./docker/php
    container_name: wallet_php
    depends_on:
      - mariadb
    expose:
      - ${PHP_FPM_PORT}
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    restart: always
    networks:
      - wallet-bridge
  mariadb:
    hostname: wallet_mariadb
    image: mariadb:latest
    container_name: wallet_mariadb
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always
    networks:
      - wallet-bridge
networks:
  wallet-bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wallet-bridge
